# -*- coding: utf-8 -*-
"""04 RAGs - Fragmentación.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LxlzBp9o6IPFREocM7oEM9_Ha9bNe_PK

# Fragmentación para RAGs

## Entorno
"""

! pip install -qU langchain-text-splitters
! pip install -qU langchain_huggingface
! pip install -qU langchain_experimental

"""## *Embeddings* locales"""

from langchain_huggingface import HuggingFaceEmbeddings

# embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

# e = embeddings.embed_query("Hello world")
# print(f"{len(e)=}, {e=}")

# ed = embeddings.embed_documents(["Hello world", "This is an example"])
# print(f"{ed=}")

embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

e = embeddings.embed_query("Hello world")
print(f"{len(e)=}, {e=}")

ed = embeddings.embed_documents(["Hello world", "This is an example"])
print(f"{ed=}")

"""# Fragmentación"""

document = """
# Bees in decline

## Diseases and parasites

Many beekeepers agree that the external invasive parasitic mite, Varroa destructor, is a serious threat to
apiculture globally. Other parasites, such as Nosema ceranae, have been found to be highly damaging to
honeybee colonies in some southern European countries. Other new viruses and pathogens are likely to put further pressure on bee colonies.

The ability of bees to resist diseases and parasites seems to be influenced by a number of factors, particularly their
nutritional status and their exposure to toxic chemicals. Some pesticides, for example, seem to weaken honeybees
that then become more susceptible to infection and parasitic infestation.

## Industrial agriculture

Pollinators, managed or wild, cannot escape the various and massive impacts of industrial agriculture: they
suffer simultaneously from the destruction of natural habitats caused by agriculture, and, because pollinators’
natural ranges inevitably overlap with industrial farming landscapes, the harmful effects of intensive agricultural practices.

Fragmentation of natural and semi-natural habitats, expansion of monocultures and lack of diversity all play
a role. Destructive practices that limit bee-nesting ability, and the spraying of herbicides and pesticides, make
industrial agriculture one of the major threats to pollinator communities globally.

On the other hand, agriculture systems that work with biodiversity and without chemicals, such as ecological
farming systems, can benefit pollinator communities, both managed and wild. By increasing habitat heterogeneity
for bees, for example, ecological mixed-cropping systems can provide additional flower resources for pollinators. This
emphasises the potential beneficial roles of ecological/organic agriculture methods.

## Climate change

Many of the predicted consequences of climate change, such as increasing temperatures, changes in rainfall
patterns and more erratic or extreme weather events, will have impacts on pollinator populations. Some of these
changes could affect pollinators individually and ultimately their communities, becoming reflected in higher extinction
rates of pollinator species.
"""

"""## Fragmentación por caracteres"""

from langchain_text_splitters import CharacterTextSplitter

text_splitter = CharacterTextSplitter(
    separator="",
    chunk_size=200,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,
    strip_whitespace=True,
)

documents = text_splitter.create_documents([document], metadatas=[{"category": "bees"}])
print(documents[0])
print("---")
print(documents[1])

"""## Fragmentación recursiva por caracteres"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    separators=["\n\n", "\n", " ", ""], # default
    chunk_size=400,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,

)

documents = text_splitter.create_documents([document], metadatas=[{"category": "bees"}])
print(documents[0])
print("---")
print(documents[1])

"""## Fragmentación específica por tipo de documento"""

from langchain_text_splitters import MarkdownTextSplitter

text_splitter = MarkdownTextSplitter(
    chunk_size=400,
    chunk_overlap=20,
    length_function=len,
    is_separator_regex=False,
)

documents = text_splitter.create_documents([document], metadatas=[{"category": "bees"}])
print(documents[0])
print("---")
print(documents[1])

from langchain_text_splitters import MarkdownHeaderTextSplitter

headers_to_split_on = [("#", "H1"),("##", "H2"),("###", "H3")]

text_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on)

documents = text_splitter.split_text(document)
print(documents[0])
print("---")
print(documents[1])

from langchain_text_splitters import MarkdownHeaderTextSplitter, RecursiveCharacterTextSplitter

headers_to_split_on = [("#", "H1"),("##", "H2"),("###", "H3")]

text_splitter = MarkdownHeaderTextSplitter(headers_to_split_on=headers_to_split_on, strip_headers=False)
md_header_splits = text_splitter.split_text(document)

###

text_splitter = RecursiveCharacterTextSplitter(chunk_size=400, chunk_overlap=30)

splits = text_splitter.split_documents(md_header_splits)
print(splits[0])
print("---")
print(splits[1])

"""## Fragmentación semántica"""

from langchain_experimental.text_splitter import SemanticChunker

text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="percentile", breakpoint_threshold_amount=95)
# text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="standard_deviation", breakpoint_threshold_amount=3)
# text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="interquartile", breakpoint_threshold_amount=1.5)
# text_splitter = SemanticChunker(embeddings, breakpoint_threshold_type="gradient", breakpoint_threshold_amount=95)

documents = text_splitter.create_documents([document])
print(documents[0])
print("---")
print(documents[1])